# Generated by Django 3.0.8 on 2020-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
