# Generated by Django 3.0.8 on 2020-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200708_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
